sudo: required
services:
  - docker
language: go
go:
  - 1.21.x
install:
  - GO111MODULE=on go install github.com/vbatts/git-validation@latest
jobs:
  include:
    - stage: PR Verify & e2e tests
      script: 
        - make travis-verify
