FROM golang
LABEL org.opencontainers.image.authors="lpabon@purestorage.com"

ENV GOPATH=/go
RUN apt update
RUN rm -rf /usr/local/go
RUN apt-get install -y unzip
RUN wget -nv https://dl.google.com/go/go1.18.6.linux-amd64.tar.gz && tar -xf go1.18.6.linux-amd64.tar.gz && mv go /usr/local  
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash 
RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.20.1/protoc-3.20.1-linux-x86_64.zip
RUN unzip protoc-3.20.1-linux-x86_64.zip -d /usr/local
RUN apt-get -y -qq install \
	python3 \
	python3-pip \
	rubygems \
	nodejs \
	make \
	git
RUN gem install grpc && gem install grpc-tools

##
## gRPC Gateway
##
RUN go install \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.10.0 \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.10.0
# Get the proto files from the grpc-gateway
RUN mkdir -p /go/src/github.com/grpc-ecosystem && \
	cd /go/src/github.com/grpc-ecosystem && \
	git clone -b v2.10.0 https://github.com/grpc-ecosystem/grpc-gateway.git
# Install swagger 2.0 to OpenApi 3.0 converter
RUN npm install -g swagger2openapi

##
## protobuf and golang gRPC compilers
##
# From https://pkg.go.dev/google.golang.org/protobuf/cmd/protoc-gen-go
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
# From https://pkg.go.dev/google.golang.org/grpc
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
# Install Google Api proto files
RUN mkdir -p /go/src/github.com/googleapis && \
	cd /go/src/github.com/googleapis && \
	git clone https://github.com/googleapis/googleapis.git

##
## proto-gen-doc
##
RUN wget https://github.com/pseudomuto/protoc-gen-doc/releases/download/v1.5.1/protoc-gen-doc_1.5.1_linux_amd64.tar.gz && \
	tar xzvf protoc-gen-doc_1.5.1_linux_amd64.tar.gz && \
	mv protoc-gen-doc /usr/local/bin

##
## grpc-framework additions
##
# Install tools
COPY ./tools/grpcfw* /usr/local/bin/
# Add protofiles
RUN mkdir -p /go/src/github.com/libopenstorage/grpc-framework
COPY . /go/src/github.com/libopenstorage/grpc-framework

# Finally, set working directory
RUN mkdir -p /go/src/code
WORKDIR /go/src/code
