FROM golang
LABEL org.opencontainers.image.authors="lpabon@purestorage.com"

# VERSIONS
# Confirm that the links are correct. Some tools change the links on newer versions
ARG GFGOLANG=1.19.4
ARG GFGRPCGATEWAY=2.14.0
ARG GFPROTOCGENDOC=1.5.1
ARG GFPROTOC=3.20.3

# Get gRPC golang versions from here: https://grpc.io/docs/languages/go/quickstart/
# Also see: https://pkg.go.dev/google.golang.org/protobuf/cmd/protoc-gen-go
ARG GFPROTOCGENGO=1.28.1
# Also see: https://pkg.go.dev/google.golang.org/grpc
ARG GFPROTOCGENGOGRPC=1.2

ENV GOPATH=/go
RUN apt update

# Install latest golang
RUN rm -rf /usr/local/go
RUN wget -nv https://dl.google.com/go/go${GFGOLANG}.linux-amd64.tar.gz && \
	tar -xf go${GFGOLANG}.linux-amd64.tar.gz && mv go /usr/local  

# Install nodejs
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash 

# Install protoc
RUN apt-get install -y unzip
RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${GFPROTOC}/protoc-${GFPROTOC}-linux-x86_64.zip
RUN unzip protoc-${GFPROTOC}-linux-x86_64.zip -d /usr/local

# Install tools from Ubuntu
RUN apt-get -y -qq install \
	python3 \
	python3-pip \
	rubygems \
	nodejs \
	make \
	git && \
	apt-get clean && \
	apt-get autoclean
RUN gem install grpc && gem install grpc-tools

##
## gRPC Gateway
##
RUN go install \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v${GFGRPCGATEWAY} \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v${GFGRPCGATEWAY}
# Get the proto files from the grpc-gateway
RUN mkdir -p /go/src/github.com/grpc-ecosystem && \
	cd /go/src/github.com/grpc-ecosystem && \
	git clone -b v${GFGRPCGATEWAY} https://github.com/grpc-ecosystem/grpc-gateway.git
# Install swagger 2.0 to OpenApi 3.0 converter
RUN npm install -g swagger2openapi

##
## protobuf and golang gRPC compilers
##
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v${GFPROTOCGENGO}
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v${GFPROTOCGENGOGRPC}
# Install Google Api proto files
RUN mkdir -p /go/src/github.com/googleapis && \
	cd /go/src/github.com/googleapis && \
	git clone https://github.com/googleapis/googleapis.git

##
## proto-gen-doc
##
RUN wget https://github.com/pseudomuto/protoc-gen-doc/releases/download/v${GFPROTOCGENDOC}/protoc-gen-doc_${GFPROTOCGENDOC}_linux_amd64.tar.gz && \
	tar xzvf protoc-gen-doc_${GFPROTOCGENDOC}_linux_amd64.tar.gz && \
	mv protoc-gen-doc /usr/local/bin

##
## grpc-framework additions
##
# Install tools
COPY ./tools/grpcfw* /usr/local/bin/
# Add protofiles
RUN mkdir -p /go/src/github.com/libopenstorage/grpc-framework
COPY . /go/src/github.com/libopenstorage/grpc-framework

# Finally, set working directory
RUN mkdir -p /go/src/code
WORKDIR /go/src/code
