#!/bin/bash

PROTOC=protoc
PROTOS_PATH=${GOPATH}/src
tmpfile=/tmp/swagger.$$

PROTO_FILE=$1
if [ $# -lt 1 ] ; then
	echo "Must provide proto file path"
	echo "Usage: grpcfw <proto file>"
	exit 1
fi
PROTOSRC_PATH=$(dirname $1)
PROTO_FILE=$1

p="${1##*/}"
PROTO_NAME=${p%.*}

	$PROTOC -I . \
		-I /usr/local/include \
		-I $PROTOS_PATH/github.com/grpc-ecosystem/grpc-gateway \
		-I $PROTOS_PATH/github.com/googleapis/googleapis \
		--go_out=. \
		--go_opt=paths=source_relative \
		--go-grpc_out=. \
		--go-grpc_opt=paths=source_relative \
		$PROTO_FILE
